# cargo-features = ["strip"]

[package]
authors = ["Rami3L <rami3l@outlook.com>"]
homepage = "https://github.com/rami3l/pacaptr"
repository = "https://github.com/rami3l/pacaptr"

keywords = ["package-management"]
categories = ["command-line-utilities"]
description = "A pacman-like wrapper for many package managers."

license = "GPL-3.0"
readme = "README.md"

edition = "2018"
include = ["LICENSE", "Cargo.toml", "src/**/*.rs", "build.rs"]
exclude = ["dist/**/*", "docs/**/*"]
# build = "build.rs"
name = "pacaptr"
version = "0.11.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
anyhow = "1.0.40"
itertools = "0.10.0"
prettytable-rs = "0.8.0"
regex = "1.4.5"

[dev-dependencies]
xshell = "0.1.9"

[dependencies]
async-trait = "0.1.48"
bytes = "1.0.1"
clap = "3.0.0-beta.2"
colored = "2.0.0"
confy = "0.4.0"
dirs = "3.0.1"
futures = "0.3.13"
is-root = "0.1.2"
itertools = "0.10.0"
once_cell = "1.7.2"
regex = { version = "1.4.5", default-features = false, features = ["std", "perf"] }
respector = "0.1.1"
serde = { version = "1.0.125", features = ["derive"] }
thiserror = "1.0.24"
tokio = { version = "1.4.0", features = [
  "io-std",
  "io-util",
  "macros",
  "process",
  "rt-multi-thread",
  "sync",
] }
tokio-stream = "0.1.5"
tokio-util = { version = "0.6.5", features = ["codec", "compat"] }
which = "4.1.0"

[package.metadata.deb]
copyright = "2020, Rami3L"
maintainer = "Rami3L <rami3l@outlook.com>"
# license-file = ["LICENSE", "4"]
assets = [
  ["target/release/pacaptr", "usr/bin/", "755"],
  ["README.md", "usr/share/doc/pacaptr/README", "644"],
]
depends = "$auto"
extended-description = """\
A Rust port of icy/pacapt, a wrapper for many package managers with \
pacman-style command syntax."""
priority = "optional"
section = "utility"

[workspace]
members = [".", "xtask"]

[profile.release]
codegen-units = 1
debug = 0
lto = true
opt-level = "z"
panic = "abort"
# strip = "symbols"
