[package]
name = "pacaptr-macros"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
litrs = "0.2.3"
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = "1.0.73"
itertools = "0.10.1"
anyhow = "1.0.42"
prettytable-rs = "0.8.0"
regex = "1.5.4"
