name: notify
on:
  # push:
  release:

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Send message to Telegram
        uses: Lukasss93/telegram-action@v1.1
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
